### ISSUE TITLE
Correct way to unsubsribe from channels in case of network failure / app going into background

### ISSUE THREAD

**Issue by escamoteur** [kerimamansaryyev/dart_pusher_channels#42]
Hi,

what is the correct way for an app to handle:

1. In case of a network failure/air plane mode to reinitialize when the network is back?
2. When I want to update my presence display depending of the app going into the background. Just unsubscribe and resubscribe or should I reinitialze the whole client and channel subscriptions?

Thanks a lot for this awesome package

**Comment by kerimamansaryyev** [comment]
Hi!
1. No need to reinitialize or reassign the client (if you didn't dispose it), it's well encapsulated. Just call `client.reconnect()`. Yes, it's better to reconnect while network changes since the connection gets interrupted.
2. Call `client.reconnect()` in this case also when app comes back from the background and organize your channel subscriptions like:
 ```
final StreamSubscription connectionSubs =
      client.onConnectionEstablished.listen((_) {
    for (final channel in allChannels) {
      // Subscribes to the channel if didn't unsubscribe from it intentionally
      channel.subscribeIfNotUnsubscribed();
    }
  });
```
With this, the stream will fire the event and automatically subscribe channels once you declare it.

**Comment by escamoteur** [comment]
Thanks for the quick reply. What if I want to intentionally unsubscribe when the app goes into background?
Am 13. Nov. 2023, 20:40 +0100 schrieb Kerim Amansaryyev ***@***.***>:

**Comment by kerimamansaryyev** [comment]
Unsubscribe what? Channel or client?

**Comment by escamoteur** [comment]
Thinking again, unsubscribing should be enough to trigger a a presence 'user left' event
Am 14. Nov. 2023, 01:32 +0100 schrieb Kerim Amansaryyev ***@***.***>:

**Comment by escamoteur** [comment]
Thanks a lot for your prompt resonses. I told our manager to buy you some coffees :-)

**Comment by kerimamansaryyev** [comment]
@escamoteur I appreciate it so much! Thank you!

**Comment by escamoteur** [comment]
Maybe adding a section to the Readme that contains what you told me here might be helpful for others
Am 15. Nov. 2023, 17:08 +0100 schrieb Kerim Amansaryyev ***@***.***>:
